# FROM node:22-slim
FROM node:22

WORKDIR /usr/src/app

RUN apt-get update && \
  apt-get install -y \
  ca-certificates \
  --no-install-recommends && \
  rm -rf /var/lib/apt/lists/*

RUN npm install -g @shopify/cli

EXPOSE 3000

CMD ["/bin/bash"]